version: "3"

services:
  NetWatchSSHAttackPod:
    build:
      context: src
    image: netwatch_ssh-attackpod:latest
    container_name: netwatch_ssh-attackpod
    environment:
      NETWATCH_COLLECTOR_AUTHORIZATINON: ${NETWATCH_COLLECTOR_AUTHORIZATINON}
      NETWATCH_COLLECTOR_URL: "https://api.netwatch.team"
    restart: unless-stopped
