version: "3"

services:
  NetWatchSSHAttackPod:
    build:
      context: src
    image: netwatch_ssh-attackpod:latest
    container_name: netwatch_ssh-attackpod
    environment:
      NETWATCH_COLLECTOR_AUTHORIZATINON: ${NETWATCH_COLLECTOR_AUTHORIZATINON}
      NETWATCH_COLLECTOR_URL: "https://api.netwatch.team"
      NETWATCH_TEST_MODE: ${NETWATCH_TEST_MODE:-false}
    restart: unless-stopped
    ports:
      - "22:22"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 750M
        reservations:
          cpus: "0.25"
          memory: 200M
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "2"'
