name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            include:
                - arch: amd64
                - arch: arm64

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/${{ matrix.arch }}

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: src
          file: src/Dockerfile
          platforms: linux/${{ matrix.arch }}
          tags: |
            netwatch_ssh-attackpod:latest-${{ matrix.arch }}
          load: true
          push: false

      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run python based integration tests via pytest
        env:
          DOCKER_IMAGE_FQN: netwatch_ssh-attackpod:latest-${{ matrix.arch }}
          DEB_HOST_ARCH: ${{ matrix.arch }}
        run: |
          pytest tests/
